spring:
  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

    remote:
      restart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    url: jdbc:mariadb://192.168.35.232:3306/jmshop_mariadb
    username: junmokang
    password: wnsah12
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        #      ddl-auto: create-drop
        use-new-id-generator-mappings: true

server:
  port: 8100

logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ../shop/jmshop_admin/logs/JmShopAdmin.log
    max-history: 30

#  level:
#    root: ERROR
#    org.springframework: INFO
#    org.springframework.web: DEBUG





